name: Auto tri des emails
 
on:

  schedule:

    - cron: "*/1 * * * *"  # toutes les 1 minute

  workflow_dispatch:       # permet un déclenchement manuel
 
jobs:

  run-script:

    runs-on: ubuntu-latest
 
    steps:

      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4

        with:

          python-version: "3.11"
 
      - name: Upgrade pip

        run: pip install --upgrade pip
 
      - name: Install dependencies

        run: pip install -r requirements.txt
 
      - name: Check installed packages

        run: pip list
 
      - name: Run tri des emails

        env:

          APP_ENV: TEST

          TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}

          TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}

          TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}

        run: python main.py
 