name: Auto tri des emails

on:
  schedule:
    - cron: "*/1 * * * *"  # toutes les 5 minutes (⚠️ GitHub n'autorise pas moins)
  workflow_dispatch:

jobs:
  tri-test:
    name: Tri (Environnement TEST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le tri (TEST)
        env:
          APP_ENV: TEST
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          APP_TENANT_ID: ${{ secrets.APP_TENANT_ID }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: python main.py

  tri-prod:
    name: Tri (Environnement PROD)
    runs-on: ubuntu-latest
    needs: tri-test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le tri (PROD)
        env:
          APP_ENV: PROD
          PROD_CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
          PROD_CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
          PROD_TENANT_ID: ${{ secrets.PROD_TENANT_ID }}
          PROD_USER_EMAIL: ${{ secrets.PROD_USER_EMAIL }}
        run: python main.py
