name: Tri automatique des emails

on:
  schedule:
    - cron: "*/1 * * * *" # Toutes les 5 minutes
  workflow_dispatch:

jobs:
  run-tri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le tri automatique
        env:
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          APP_TENANT_ID: ${{ secrets.APP_TENANT_ID }}
        run: python main.py
