name: Auto tri des emails

on:
  schedule:
    - cron: "*/1 * * * *"  # Exécution toutes les 5 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install msal requests

      - name: Exécuter le script de tri
        env:
          APP_ENV: TEST
          OUTLOOK_USER_ID: ${{ secrets.OUTLOOK_USER_ID }}
          TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
          TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
          TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
        run: python main.py
